server:
  port: 2000
spring:
  application:
    name: crowdfunding-mysql
  datasource:
    name: crowdfunding-db
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/crowdfunding?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: Hypocritical Fish
    password: lovexin
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml

logging:
  level:
    com.hypocriticalfish.crowdfunding.mapper: debug
    com.hypocriticalfish.crowdfunding.test: debug