server:
  port: 5000

spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
  application:
    name: crowdfunding-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: localhost
    password: lovexin
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

aliyun:
  oss:
    access-key-id: LTAI5t7ZEkXZ5hSxqbyvdVkC
    access-key-secret: ZHc7myqAMyTeeelPP0DenkZsZrScgi
    bucket-domain: http://hypofish-crowdfunding.oss-cn-shanghai.aliyuncs.com
    bucket-name: hypofish-crowdfunding
    end-point: http://oss-cn-shanghai.aliyuncs.com