server:
  port: 3000

spring:
  application:
    name: crowdfunding-redis
  redis:
    host: localhost
    password: lovexin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka