server:
  port: 6000

spring:
  application:
    name: crowdfunding-order
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: localhost
    password: lovexin
  session:
    store-type: redis


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka